# Generated by Django 4.0.2 on 2023-03-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_society_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_notice',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
