# Generated by Django 4.0.2 on 2023-03-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_society_notice_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency_notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_notice', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
