# Generated by Django 4.0.2 on 2023-03-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_emergency_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common_plot_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('event_name', models.CharField(max_length=100)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('added_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
